import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderNav from "../components/ui/HeaderNav";

const satoshi = localFont({
  src: "../../public/fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
  weight: "100 900", // covers the full weight range
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} antialiased`}>
        <HeaderNav />
        {children}
      </body>
    </html>
  );
}
